CREATE DATABASE ALEXANDRIA;

USE ALEXANDRIA;

CREATE TABLE T_LIVRO (
    LIV_CODIGO INT AUTO_INCREMENT PRIMARY KEY,  
    LIV_TITULO VARCHAR(255) NULL,
    LIV_DISPONIBILIDADE BOOLEAN NULL,
    LIV_SINOPSE VARCHAR(255) NULL,
    LIV_MEDIA_AVALIACAO DECIMAL(5,2) NULL
);

CREATE TABLE T_AUTOR (
    AUT_CODIGO INT AUTO_INCREMENT PRIMARY KEY, 
    AUT_NOME VARCHAR(255) NOT NULL
);

ALTER TABLE T_LIVRO
ADD AUT_CODIGO INT;

ALTER TABLE T_LIVRO
ADD CONSTRAINT FK_LIVRO_AUTOR
FOREIGN KEY (AUT_CODIGO) REFERENCES T_AUTOR(AUT_CODIGO);

CREATE TABLE T_LIVRO_AUTOR (
    LIV_CODIGO INT,
    AUT_CODIGO INT,
    PRIMARY KEY (LIV_CODIGO, AUT_CODIGO),
    FOREIGN KEY (LIV_CODIGO) REFERENCES T_LIVRO(LIV_CODIGO),
    FOREIGN KEY (AUT_CODIGO) REFERENCES T_AUTOR(AUT_CODIGO)
);

CREATE TABLE T_USUARIO (
    USU_CODIGO INT AUTO_INCREMENT PRIMARY KEY,  
    USU_NOME VARCHAR(255) NOT NULL,
    USU_EMAIL VARCHAR(255) NULL
);

CREATE TABLE T_EMPRESTIMO (
    EMP_CODIGO INT AUTO_INCREMENT PRIMARY KEY,  
    LIV_CODIGO INT NULL,
    USU_CODIGO INT NULL,
    EMP_DATA_INICIO DATETIME NULL,
    EMP_DATA_FIM DATETIME NULL,
    EMP_DATA_DEVOLUCAO DATETIME NULL,
    EMP_ATIVO BOOLEAN NULL,
    FOREIGN KEY (LIV_CODIGO) REFERENCES T_LIVRO(LIV_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);

CREATE TABLE T_MULTA (
   MUL_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
   EMP_CODIGO INT NULL,
   MUL_ATIVO BOOLEAN NULL,
   MUL_DATA_VERIFICACAO DATETIME NULL,
   MUL_DIAS_ATRASO INT NULL,
   MUL_VALOR_A_PAGAR DECIMAL(10, 2) NULL,
   FOREIGN KEY (EMP_CODIGO) REFERENCES T_EMPRESTIMO(EMP_CODIGO)
);

-- Alterando a tabela T_USUARIO para adicionar novas colunas
ALTER TABLE T_USUARIO 
ADD USU_SENHA VARCHAR(255) NULL,
ADD USU_LOGIN VARCHAR(255) NULL,
ADD USU_TIPO INT NULL;

-- Criando a tabela T_GENERO
CREATE TABLE T_GENERO (
   GEN_CODIGO INT AUTO_INCREMENT PRIMARY KEY,
   GEN_NOME VARCHAR(255) NULL
);

-- Criando a tabela T_COMENTARIO
CREATE TABLE T_COMENTARIO (
    COM_CODIGO INT AUTO_INCREMENT PRIMARY KEY,  
    USU_CODIGO INT NULL,
    LIV_CODIGO INT NULL,
    COM_DESCRICAO VARCHAR(255) NULL,
    COM_DATA DATETIME NULL,
    FOREIGN KEY (LIV_CODIGO) REFERENCES T_LIVRO(LIV_CODIGO),
    FOREIGN KEY (USU_CODIGO) REFERENCES T_USUARIO(USU_CODIGO)
);
